security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
            fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
            main:
                pattern: ^/
                form_login:
                    provider: fos_userbundle
                    login_path: /login
                    check_path: /login_check
                    default_target_path: /bien
                    always_use_default_target_path: true
                    csrf_provider: form.csrf_provider

                logout:
                    path: /logout
                    target: /login
                anonymous:    true

                switch_user: { role: ROLE_ADMIN }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bien, role: ROLE_USER }
        - { path: ^/responsable, role: ROLE_USER }

